package constants;

/**
 * Key name of all the properties mentioned in property file. <br/>
 * <br/>
 * Jun 8, 2022
 *
 * @version 1.0
 */
public enum ConfigMap {
  URLFORENV,
  TESTERNAME,
  IP,
  APPIUMJS,
  NODEJS,
  APPPACKAGE,
  APPACTIVITY,
  APPNAME,
  ENVIRONMENT,
  RUNMODE,
  REMOTEURL,
  DELETEOLDREPORTS,
  NUMBEROFDAYS,
  OVERRIDEREPORTS,
  PASSEDSCREENSHOT,
  RETRYFAILEDTESTCASES,
  USEELK,
  ELKSUITEURL,
  SENDMAILAFTEREXECUTION,
  SENDMAILUSING,
  SENDERSID,
  EMAILPASSWORD,
  RECEIVERSID,
  AUTOSTARTEMULATOR,
  AUTOKILLEMULATOR,
  EMULATORNAME,
  ADVPACKAGE,
  AUTODELETETESTEMULATOR,
  APPIUMJSEXE, NODEJSEXE,
}
